### PR TITLE
Interactive

### PR DESCRIPTION
**Pull request by Anvi98**
Add 2 new JavaScript files and import them as modules:
=> one will contain methods related to drag / drop and sorting functionality.
=> the other will contain methods related to the status updates (completed: true / false).
Add event listeners to list items (dragstart, dragover, drop) and to checkbox (change).
Update items object's values for index and completed keys upon user actions.
Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
Hi @Anvi98, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have ESlint as part of jobs in the `.github/workflows/linters.yml` configuration file. This is a JavaScript project, therefore, you should have GitHub Actions config set up for JS (ESLint). Kindly update the linters configuration by adding the [JavaScript linter](https://github.com/microverseinc/linters-config/tree/master/javascript).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Anvi98** [comment]
Mr.teekaytech  if you can please check very well, you could see I have installed the Github actions and all tests passed successfully. 
My workflows are okay please, check carefully Before.

**Comment by teekaytech** [comment]
> Mr.teekaytech if you can please check very well, you could see I have installed the Github actions and all tests passed successfully.
> My workflows are okay please, check carefully Before.

Hi @Anvi98, 
I did not say that you did not set up the GitHub Actions or the tests are not passing. All I'm saying is, you should have ESlint as part of the checks, which at the moment, is not among your configured checks. Please, check my comments carefully :blush:

**Comment by Anvi98** [comment]
I have already Added the ESLint

**Review by smcommits — APPROVED** [review]
### Status: Approved 👍🏽 

Hi @Anvi98, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
